"""Redesign messages table

Revision ID: 8325765c802f
Revises: 755e6e2915ce
Create Date: 2026-07-07 13:45:10.433848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8325765c802f'
down_revision: Union[str, Sequence[str], None] = '755e6e2915ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('role', sa.String(length=20), nullable=False))
    op.add_column('messages', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('messages', sa.Column('agent_name', sa.String(length=100), nullable=True))
    op.drop_column('messages', 'message')
    op.drop_column('messages', 'sender')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('messages', 'agent_name')
    op.drop_column('messages', 'content')
    op.drop_column('messages', 'role')
    # ### end Alembic commands ###
